# Generated by Django 5.1.6 on 2026-03-31 23:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_service", "0006_alter_service_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Description complète du service"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="resume",
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Résumé"),
        ),
    ]
