# Generated by Django 5.1.6 on 2026-04-01 00:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_service", "0007_alter_service_content_alter_service_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="domaine",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Domaine"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="stack",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Stack technique"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="statut",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("in_progress", "En cours"),
                    ("completed", "Terminé"),
                    ("published", "Publié"),
                ],
                default="published",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Description complète du service"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="resume",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Résumé"
            ),
        ),
    ]
