# Generated by Django 5.1.6 on 2026-04-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_service", "0008_service_domaine_service_stack_service_statut_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="statut",
            field=models.CharField(
                blank=True,
                choices=[
                    ("planning", "En planification"),
                    ("in_progress", "En cours"),
                    ("paused", "En pause"),
                    ("deployed", "Déployé"),
                    ("completed", "Terminé"),
                    ("archived", "Archivé"),
                ],
                default="",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
