# Generated by Django 5.1.6 on 2026-04-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_service", "0010_service_new_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Durée de session (ex: '1 heure', '2 jours')",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="duree",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Durée estimée du projet (ex: '4–8 semaines')",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="statut",
            field=models.CharField(
                blank=True,
                choices=[
                    ("disponible", "Disponible"),
                    ("bientot_disponible", "Bientôt disponible"),
                    ("complet", "Complet"),
                    ("planning", "En planification"),
                    ("in_progress", "En cours"),
                    ("paused", "En pause"),
                    ("deployed", "Déployé"),
                    ("completed", "Terminé"),
                    ("archived", "Archivé"),
                ],
                default="",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
