# Generated by Django 5.1.6 on 2026-03-31 23:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0009_alter_blogpost_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Contenu de l'article"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="resume",
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Résumé"),
        ),
    ]
