# Generated by Django 5.1.6 on 2026-04-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0013_update_blogpost_status_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="tags",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Tags (separes par des virgules)",
            ),
        ),
    ]
