# Generated by Django 5.1.6 on 2026-04-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0014_alter_blogpost_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="demo_url",
            field=models.URLField(blank=True, verbose_name="Lien demo"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="github_url",
            field=models.URLField(blank=True, verbose_name="Lien GitHub"),
        ),
    ]
