# Generated by Django 5.1.6 on 2026-03-31 23:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_projet", "0007_alter_project_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Contenu détaillé"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="resume",
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Résumé"),
        ),
    ]
