# Generated by Codex on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_projet", "0009_project_domaine_project_stack_project_statut_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStackItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("icon", models.ImageField(blank=True, null=True, upload_to="project_stack/", verbose_name="Logo")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("project", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="stack_items", to="app_projet.project", verbose_name="Projet")),
            ],
            options={
                "verbose_name": "Stack projet",
                "verbose_name_plural": "Stacks projet",
                "ordering": ("order", "id"),
            },
        ),
    ]
