# Generated by Codex on 2026-03-31

from django.db import migrations, models


def migrate_project_statuses(apps, schema_editor):
    Project = apps.get_model("app_projet", "Project")
    mapping = {
        "draft": "planning",
        "in_progress": "in_progress",
        "completed": "archived",
        "published": "deployed",
    }
    for project in Project.objects.all():
        project.statut = mapping.get(project.statut, "")
        project.save(update_fields=["statut"])


def reverse_project_statuses(apps, schema_editor):
    Project = apps.get_model("app_projet", "Project")
    mapping = {
        "planning": "draft",
        "in_progress": "in_progress",
        "paused": "",
        "deployed": "published",
        "archived": "completed",
        "": "",
    }
    for project in Project.objects.all():
        project.statut = mapping.get(project.statut, "")
        project.save(update_fields=["statut"])


class Migration(migrations.Migration):

    dependencies = [
        ("app_projet", "0010_projectstackitem"),
    ]

    operations = [
        migrations.RunPython(migrate_project_statuses, reverse_project_statuses),
        migrations.AlterField(
            model_name="project",
            name="statut",
            field=models.CharField(
                blank=True,
                choices=[
                    ("planning", "En planification"),
                    ("in_progress", "En cours"),
                    ("paused", "En pause"),
                    ("deployed", "Déployé"),
                    ("archived", "Archivé"),
                ],
                default="",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
