# Generated by Django 5.1.6 on 2026-04-01 03:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_projet", "0012_alter_project_status_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Contenu detaille"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="demo_url",
            field=models.URLField(blank=True, verbose_name="Lien demo"),
        ),
    ]
