# Generated by Django 5.1.6 on 2026-04-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_projet", "0014_project_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="statut",
            field=models.CharField(
                blank=True,
                choices=[
                    ("disponible", "Disponible"),
                    ("bientot_disponible", "Bientôt disponible"),
                    ("complet", "Complet"),
                    ("planning", "En planification"),
                    ("in_progress", "En cours"),
                    ("paused", "En pause"),
                    ("deployed", "Déployé"),
                    ("completed", "Terminé"),
                    ("archived", "Archivé"),
                ],
                default="",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
