# Generated by Django 5.1.6 on 2026-04-01 00:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_acceuil",
            "0039_alter_education_details_alter_experience_details_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="details",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Détails de la formation"
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="details",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Détails de l'expérience"
            ),
        ),
        migrations.AlterField(
            model_name="sectionitem",
            name="details",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Détails"
            ),
        ),
        migrations.AlterField(
            model_name="siteprofile",
            name="bio",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, verbose_name="Bio"
            ),
        ),
        migrations.AlterField(
            model_name="siteprofile",
            name="blog_home_intro",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, verbose_name="Texte d'introduction Blog (Accueil)"
            ),
        ),
        migrations.AlterField(
            model_name="siteprofile",
            name="blog_page_intro",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, verbose_name="Texte d'introduction page Blog"
            ),
        ),
        migrations.AlterField(
            model_name="siteprofile",
            name="contact_intro_text",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, verbose_name="Texte d'introduction Contact"
            ),
        ),
        migrations.AlterField(
            model_name="siteprofile",
            name="projects_home_intro",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, verbose_name="Texte d'introduction Projets (Accueil)"
            ),
        ),
        migrations.AlterField(
            model_name="siteprofile",
            name="projects_page_intro",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, verbose_name="Texte d'introduction page Projets"
            ),
        ),
        migrations.AlterField(
            model_name="siteprofile",
            name="services_home_intro",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, verbose_name="Texte d'introduction Services (Accueil)"
            ),
        ),
        migrations.AlterField(
            model_name="siteprofile",
            name="services_page_intro",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, verbose_name="Texte d'introduction page Services"
            ),
        ),
    ]
